/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/
import { BuildingConfig, BuildingType, BuildingCategory, Milestone } from './types';

// Map Settings
export const GRID_SIZE = 50;
export const CHUNK_SIZE = 5;

// Game Settings
export const DAY_MS = 5000; // 1 in-game day = 5 real seconds
export const INITIAL_MONEY = 1500;

export const EconomyConfig = {
  passiveSubsidy: 10,
  taxPerPerson: 1,
  moveInBonus: 5,
  shopSmallIncome: 10,
  shopLargeIncome: 30,
  mallIncome: 100,
  financialCenterIncome: 350,
  factorySmallIncome: 20,
  factoryLargeIncome: 70,
  chemicalPlantIncome: 250,
  highTechFactoryIncome: 1000,
  levelIncomeMultiplier: 0.05, // +5% per level
};

export const MILESTONES: Milestone[] = [
  { level: 1, name: 'Лагерь', requiredPop: 0 },
  { level: 2, name: 'Деревня', requiredPop: 50 },
  { level: 3, name: 'Поселок', requiredPop: 150 },
  { level: 4, name: 'Городок', requiredPop: 500 },
  { level: 5, name: 'Райцентр', requiredPop: 1200 },
  { level: 6, name: 'Город', requiredPop: 3000 },
  { level: 7, name: 'Мегаполис', requiredPop: 6000 },
  { level: 8, name: 'Столица', requiredPop: 10000 },
];

export const BUILDINGS: Record<BuildingType, BuildingConfig> = {
  [BuildingType.None]: {
    type: BuildingType.None,
    category: BuildingCategory.Infrastructure,
    cost: 25, // Снос
    name: 'Снести',
    description: 'Очистить клетку ($25)',
    color: '#ef4444',
    popGen: 0,
    incomeGen: 0,
    minLevel: 1,
    width: 1, height: 1,
  },
  [BuildingType.BuyLand]: {
    type: BuildingType.BuyLand,
    category: BuildingCategory.Infrastructure,
    cost: 500, // Базовая стоимость, будет увеличиваться программно
    name: 'Территория',
    description: 'Расширить',
    color: '#22c55e',
    popGen: 0,
    incomeGen: 0,
    minLevel: 1,
    width: 1, height: 1,
  },
  [BuildingType.Road]: {
    type: BuildingType.Road,
    category: BuildingCategory.Infrastructure,
    cost: 10,
    name: 'Дорога',
    description: 'Связывает здания',
    color: '#374151',
    popGen: 0,
    incomeGen: 0,
    minLevel: 1,
    width: 1, height: 1,
  },
  [BuildingType.HouseSmall]: {
    type: BuildingType.HouseSmall,
    category: BuildingCategory.Residential,
    cost: 50,
    name: 'Малый дом',
    description: '+1 Жит/день. Макс: 5',
    color: '#f87171',
    popGen: 1,
    incomeGen: 0,
    minLevel: 1,
    width: 1, height: 1,
  },
  [BuildingType.HouseMedium]: {
    type: BuildingType.HouseMedium,
    category: BuildingCategory.Residential,
    cost: 150,
    name: 'Средний дом',
    description: '+3 Жит/день. Макс: 15',
    color: '#ef4444',
    popGen: 3,
    incomeGen: 0,
    minLevel: 2,
    width: 1, height: 2,
  },
  [BuildingType.HouseLarge]: {
    type: BuildingType.HouseLarge,
    category: BuildingCategory.Residential,
    cost: 600,
    name: 'Большой дом',
    description: '+6 Жит/день. Макс: 30',
    color: '#b91c1c',
    popGen: 6,
    incomeGen: 0,
    minLevel: 3,
    width: 2, height: 2,
  },
  [BuildingType.ShopSmall]: {
    type: BuildingType.ShopSmall,
    category: BuildingCategory.Commercial,
    cost: 100,
    name: 'Рынок',
    description: `+$${EconomyConfig.shopSmallIncome}/день`,
    color: '#60a5fa',
    popGen: 0,
    incomeGen: EconomyConfig.shopSmallIncome,
    minLevel: 1,
    width: 2, height: 2,
  },
  [BuildingType.ShopLarge]: {
    type: BuildingType.ShopLarge,
    category: BuildingCategory.Commercial,
    cost: 1000,
    name: 'Супермаркет',
    description: `+$${EconomyConfig.shopLargeIncome}/день`,
    color: '#2563eb',
    popGen: 0,
    incomeGen: EconomyConfig.shopLargeIncome,
    minLevel: 3,
    width: 2, height: 3,
  },
  [BuildingType.Mall]: {
    type: BuildingType.Mall,
    category: BuildingCategory.Commercial,
    cost: 8000,
    name: 'Молл',
    description: `+$${EconomyConfig.mallIncome}/день`,
    color: '#1d4ed8',
    popGen: 0,
    incomeGen: EconomyConfig.mallIncome,
    minLevel: 5,
    width: 3, height: 3,
  },
  [BuildingType.FinancialCenter]: {
    type: BuildingType.FinancialCenter,
    category: BuildingCategory.Commercial,
    cost: 40000,
    name: 'Финансовый центр',
    description: `+$${EconomyConfig.financialCenterIncome}/день`,
    color: '#1e3a8a',
    popGen: 0,
    incomeGen: EconomyConfig.financialCenterIncome,
    minLevel: 8,
    width: 3, height: 4,
  },
  [BuildingType.FactorySmall]: {
    type: BuildingType.FactorySmall,
    category: BuildingCategory.Industrial,
    cost: 200,
    name: 'Фабрика',
    description: `+$${EconomyConfig.factorySmallIncome}/день, -Счастье`,
    color: '#facc15',
    popGen: 0,
    incomeGen: EconomyConfig.factorySmallIncome,
    minLevel: 1,
    width: 2, height: 2,
  },
  [BuildingType.FactoryLarge]: {
    type: BuildingType.FactoryLarge,
    category: BuildingCategory.Industrial,
    cost: 2000,
    name: 'Огромный Завод',
    description: `+$${EconomyConfig.factoryLargeIncome}/день, -Счастье`,
    color: '#b45309',
    popGen: 0,
    incomeGen: EconomyConfig.factoryLargeIncome,
    minLevel: 4,
    width: 2, height: 3,
  },
  [BuildingType.ChemicalPlant]: {
    type: BuildingType.ChemicalPlant,
    category: BuildingCategory.Industrial,
    cost: 15000,
    name: 'Химзавод',
    description: `+$${EconomyConfig.chemicalPlantIncome}/день, --Счастье`,
    color: '#78350f',
    popGen: 0,
    incomeGen: EconomyConfig.chemicalPlantIncome,
    minLevel: 5,
    width: 3, height: 3,
  },
  [BuildingType.HighTechFactory]: {
    type: BuildingType.HighTechFactory,
    category: BuildingCategory.Industrial,
    cost: 80000,
    name: 'Нанотех Комплекс',
    description: `+$${EconomyConfig.highTechFactoryIncome}/день, -Счастье`,
    color: '#451a03',
    popGen: 0,
    incomeGen: EconomyConfig.highTechFactoryIncome,
    minLevel: 8,
    width: 4, height: 4,
  },
  [BuildingType.ParkSmall]: {
    type: BuildingType.ParkSmall,
    category: BuildingCategory.Decorations,
    cost: 100,
    name: 'Сквер',
    description: 'Счастье++',
    color: '#4ade80',
    popGen: 0,
    incomeGen: 0,
    minLevel: 1,
    width: 1, height: 1,
  },
  [BuildingType.ParkLarge]: {
    type: BuildingType.ParkLarge,
    category: BuildingCategory.Decorations,
    cost: 800,
    name: 'Городской Парк',
    description: 'Счастье++++',
    color: '#16a34a',
    popGen: 0,
    incomeGen: 0,
    minLevel: 3,
    width: 2, height: 2,
  },
  [BuildingType.AquaPark]: {
    type: BuildingType.AquaPark,
    category: BuildingCategory.Decorations,
    cost: 5000,
    name: 'Аквапарк',
    description: 'Счастье+++++',
    color: '#22d3ee',
    popGen: 0,
    incomeGen: 0,
    minLevel: 5,
    width: 3, height: 3,
  },
  [BuildingType.AmusementPark]: {
    type: BuildingType.AmusementPark,
    category: BuildingCategory.Decorations,
    cost: 20000,
    name: 'Парк аттракционов',
    description: 'Счастье++++++',
    color: '#ec4899',
    popGen: 0,
    incomeGen: 0,
    minLevel: 7,
    width: 4, height: 4,
  },
};
